CREATE TABLE IF NOT EXISTS tournament(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    acronym TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);