services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - ${DB_PORT}:5432
    secrets:
      - db_password
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - PGUSER=${DB_USERNAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=${DB_NAME}
    command:
      [
        "-c",
        "ssl=on",
        "-c",
        "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem",
        "-c",
        "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
      ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: web-server.Dockerfile
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_password
    environment:
      - APP_ENVIRONMENT=development
      - APP_DATABASE__USERNAME=${DB_USERNAME}
      - APP_DATABASE__PASSWORD_FILE=/run/secrets/db_password
      - APP_DATABASE__DATABASE_NAME=${DB_NAME}
      - APP_DATABASE__HOST=db
      - APP_DATABASE__PORT=5432

secrets:
  db_password:
    file: secrets/db_password.txt
