FROM node:16-bullseye-slim
WORKDIR /app

RUN apt-get update && apt-get install -y git

COPY ./frontend/dashboard ./dashboard
COPY ./frontend/fields ./fields

WORKDIR /app/dashboard
RUN corepack enable \
    && corepack prepare yarn@stable --activate \
    && yarn set version 3.3.0 \
    && yarn install
RUN yarn

COPY ./.env.production ./dashboard/.env.production
RUN yarn build
