FROM python:3.10-slim-bullseye
WORKDIR /app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY ./backend/api ./api
COPY ./backend/common ./common
COPY ./backend/start_api.py ./start_api.py
