mysql -u root --password=$MYSQL_ROOT_PASSWORD <<EOF
CREATE USER IF NOT EXISTS '$MYSQL_USER' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE DATABASE IF NOT EXISTS $MYSQL_MESSAGE_DATABASE;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER';
GRANT ALL PRIVILEGES ON $MYSQL_MESSAGE_DATABASE.* TO '$MYSQL_USER';
FLUSH PRIVILEGES;
EOF