[package]
name = "tosurnament-config"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
figment = { version = "0.10.*", features = ["env", "yaml"] }
figment_file_provider_adapter = "0.1.*"
serde = { version = "1.0.*", features = ["derive"] }
thiserror = "2.0.*"

[dev-dependencies]
serial_test = "3.5.*"
tosurnament-tmpenv = { path = "../tmpenv" }
