[package]
name = "tosurnament-telemetry"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
thiserror = "2.0.*"
tracing = { version = "0.1.*", features = ["log"] }
tracing-bunyan-formatter = "0.3.*"
tracing-log = "0.2.*"
tracing-subscriber = {
  version = "0.3.*",
  features = [
    "env-filter",
    "registry",
  ]
}
