name: tosurnament-development
services:
  irc:
    build:
      context: ..
      dockerfile: docker/test/test-irc.Dockerfile
    ports:
      - 6667:6667
  web:
    environment:
      - APP_REFCHAT__HOST=irc
    depends_on:
      - irc
