[package]
name = "tosurnament-api"
version = "0.1.0"
authors = ["Spartan Plume <spartan.plume@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "tosurnament-api"

[features]
test-utils = ["sqlx", "uuid", "reqwest"]

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["macros"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "serde",
] }
lazy_static = "1.4"
ormlite = "0.19"
reqwest = { version = "0.11", features = ["json"], optional = true }
serde = { version = "1", features = ["derive"] }
serde-aux = "4"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
], optional = true }
tera = "1"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
tracing = { version = "0.1", features = ["log"] }
tosurnament-core = { path = "../../libs/core" }
tosurnament-config = { path = "../../libs/config" }
tosurnament-telemetry = { path = "../../libs/telemetry" }
uuid = { version = "1", features = ["v4"], optional = true }

[dev-dependencies]
once_cell = "1"
tosurnament-api = { path = ".", features = ["test-utils"] }
tosurnament-core = { path = "../../libs/core", features = ["test-utils"] }
