name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: ./tosurnament --test
